#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jan 28 14:01:20 2019

@author: laurevalery
"""

class Article:
    
    def lire():
        fichier = open("data.txt", "r")
        print(fichier)
        
    def ecriture():
        fichier = open("data.txt", "w")
        fichier.write("Bonjour monde")
        fichier.close()
    
        
    
        
